baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "aj2duncan.com"
theme = "hugo-sustain"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
math = "true"

[permalinks]
    post = "/blog/:slug/"

[[menu.main]]
    name = "Research"
    url = "/research/"
[[menu.main]]
    name = "Blog"
    url = "/blog/"

[params]
    description = "My personal webpage built through Hugo and blogdown."
    front = "images/front.jpg"
    author = "Andrew Duncan"
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.9.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    custom_css = ["css/custom.css", "css/custom_leaflet.css"]

[params.social]
  github        = "aj2duncan"
  twitter       = "aj2duncan"
